apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-go-prod
spec:
    selector:
        matchLabels:
            app: app-go-prod
    template:
        metadata:
            labels:
                app: app-go-prod
        spec:
            containers:
            -   name: app-go-prod
                image: img-app-deployment
                ports:
                -   containerPort: 80