apiVersion: apps/v1
kind: Deployment
metadata:
    name: app_go
spec:
    selector:
        matchLabels:
            app: app_go
    template:
        metadata:
            labels:
                app: app_go
        spec:
            containers:
            -   name: app_go
                image: img-app-deployment
                ports:
                -   containerPort: 80