apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-server-go
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-go
    template:
        metadata:
            labels:
                app: app-go
        spec:
            containers:
            -   name: app-go
                image: thiagomoraes/desafio-ci-cd
                ports:
                -   containerPort: 80